src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AddressRepository::class)
 */
class Address
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $number;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $way;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $street_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=Company::class, inversedBy="addresses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $company;

    /**
     * @ORM\OneToMany(targetEntity=HistoricalAddress::class, mappedBy="address")
     */
    private $historicalAddresses;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->historicalAddresses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(?int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getWay(): ?string
    {
        return $this->way;
    }

    public function setWay(string $way): self
    {
        $this->way = $way;

        return $this;
    }

    public function getStreetName(): ?string
    {
        return $this->street_name;
    }

    public function setStreetName(string $street_name): self
    {
        $this->street_name = $street_name;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    /**
     * @return Collection|HistoricalAddress[]
     */
    public function getHistoricalAddresses(): Collection
    {
        return $this->historicalAddresses;
    }

    public function addHistoricalAddress(HistoricalAddress $historicalAddress): self
    {
        if (!$this->historicalAddresses->contains($historicalAddress)) {
            $this->historicalAddresses[] = $historicalAddress;
            $historicalAddress->setAddress($this);
        }

        return $this;
    }

    public function removeHistoricalAddress(HistoricalAddress $historicalAddress): self
    {
        if ($this->historicalAddresses->removeElement($historicalAddress)) {
            // set the owning side to null (unless already changed)
            if ($historicalAddress->getAddress() === $this) {
                $historicalAddress->setAddress(null);
            }
        }

        return $this;
    }
}

src/Entity/Company.php
<?php

namespace App\Entity;

use App\Repository\CompanyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CompanyRepository::class)
 */
class Company
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=15)
     * @Assert\Length(min=9, max=15)
     */
    private $siren_number;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $city_registration;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_registration;

    /**
     * @ORM\Column(type="integer")
     */
    private $share_social;

    /**
     * @ORM\OneToMany(targetEntity=Address::class, mappedBy="company")
     */
    private $addresses;

    /**
     * @ORM\ManyToOne(targetEntity=Jurisdiction::class, inversedBy="companies")
     * @ORM\JoinColumn(nullable=false)
     */
    private $jurisdiction;

    /**
     * @ORM\OneToMany(targetEntity=HistoricalCompany::class, mappedBy="company")
     */
    private $historicalCompanies;

    /**
     * @ORM\OneToMany(targetEntity=HistoricalAddress::class, mappedBy="company")
     */
    private $historicalAddresses;


    public function __construct()
    {
        $this->date_registration = new \DateTime();
        $this->addresses = new ArrayCollection();
        $this->historicalCompanies = new ArrayCollection();
        $this->historicalAddresses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSirenNumber(): ?string
    {
        return $this->siren_number;
    }

    public function setSirenNumber(string $siren_number): self
    {
        $this->siren_number = $siren_number;

        return $this;
    }

    public function getCityRegistration(): ?string
    {
        return $this->city_registration;
    }

    public function setCityRegistration(string $city_registration): self
    {
        $this->city_registration = $city_registration;

        return $this;
    }

    public function getDateRegistration(): ?\DateTimeInterface
    {
        return $this->date_registration;
    }

    public function setDateRegistration(\DateTimeInterface $date_registration): self
    {
        $this->date_registration = $date_registration;

        return $this;
    }

    public function getShareSocial(): ?int
    {
        return $this->share_social;
    }

    public function setShareSocial(int $share_social): self
    {
        $this->share_social = $share_social;

        return $this;
    }

    /**
     * @return Collection|Address[]
     */
    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    public function addAddress(Address $address): self
    {
        if (!$this->addresses->contains($address)) {
            $this->addresses[] = $address;
            $address->setCompany($this);
        }

        return $this;
    }

    public function removeAddress(Address $address): self
    {
        if ($this->addresses->removeElement($address)) {
            // set the owning side to null (unless already changed)
            if ($address->getCompany() === $this) {
                $address->setCompany(null);
            }
        }

        return $this;
    }

    public function getJurisdiction(): ?Jurisdiction
    {
        return $this->jurisdiction;
    }

    public function setJurisdiction(?Jurisdiction $jurisdiction): self
    {
        $this->jurisdiction = $jurisdiction;

        return $this;
    }

    /**
     * @return Collection|HistoricalCompany[]
     */
    public function getHistoricalCompanies(): Collection
    {
        return $this->historicalCompanies;
    }

    public function addHistoricalCompany(HistoricalCompany $historicalCompany): self
    {
        if (!$this->historicalCompanies->contains($historicalCompany)) {
            $this->historicalCompanies[] = $historicalCompany;
            $historicalCompany->setCompany($this);
        }

        return $this;
    }

    public function removeHistoricalCompany(HistoricalCompany $historicalCompany): self
    {
        if ($this->historicalCompanies->removeElement($historicalCompany)) {
            // set the owning side to null (unless already changed)
            if ($historicalCompany->getCompany() === $this) {
                $historicalCompany->setCompany(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|HistoricalAddress[]
     */
    public function getHistoricalAddresses(): Collection
    {
        return $this->historicalAddresses;
    }

    public function addHistoricalAddress(HistoricalAddress $historicalAddress): self
    {
        if (!$this->historicalAddresses->contains($historicalAddress)) {
            $this->historicalAddresses[] = $historicalAddress;
            $historicalAddress->setCompany($this);
        }

        return $this;
    }

    public function removeHistoricalAddress(HistoricalAddress $historicalAddress): self
    {
        if ($this->historicalAddresses->removeElement($historicalAddress)) {
            // set the owning side to null (unless already changed)
            if ($historicalAddress->getCompany() === $this) {
                $historicalAddress->setCompany(null);
            }
        }

        return $this;
    }
}

src/Controller/HistoricalController.php
<?php

namespace App\Controller;

use App\Entity\HistoricalSearch;
use App\Form\HistoricalSearchType;
use App\Repository\HistoricalCompanyRepository;
use App\Repository\HistoricalAddressRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/historical")
 */
class HistoricalController extends AbstractController
{
    /**
     * @var HistoricalCompanyRepository
    */
    private $historicalCompanyRepository;

    /**
     * @var HistoricalAddressRepository
    */
    private $historicalAddressRepository;

    public function __construct(HistoricalCompanyRepository $historicalCompanyRepository, HistoricalAddressRepository $historicalAddressRepository)
    {
        $this->historicalCompanyRepository = $historicalCompanyRepository;
        $this->historicalAddressRepository = $historicalAddressRepository;
    }

    /**
     * @Route("/{id}", name="historical_show", methods={"GET"})
     */
    public function show(Request $request, $id): Response
    {
        $search = new HistoricalSearch();

        $form = $this->createForm(HistoricalSearchType::class, $search);
        $form->handleRequest($request);

        $companyInfos = $this->historicalCompanyRepository->findByCompanyAndDate($id, $search);
        $addressInfos = $this->historicalAddressRepository->findByCompanyAndDate($id, $search);

        return $this->render('historical/show.html.twig', [
            'companyInfos'   => $companyInfos,
            'addressInfos'   => $addressInfos,
            'form' => $form->createView()
        ]);
    }
}

templates/historical/_address.html.twig
    <tr>
        <td>{{ addressInfo.number }}</td>
        <td>{{ addressInfo.way }}</td>
        <td>{{ addressInfo.streetName }}</td>
        <td>{{ addressInfo.postalCode }}</td>
        <td>{{ addressInfo.city }}</td>
        <td>{{ addressInfo.createdAt|date('d-m-Y H:i:s') }}</td>
    </tr>

templates/historical/_company.html.twig
    <tr>
        <td>{{ companyInfo.name }}</td>
        <td>{{ companyInfo.sirenNumber }}</td>
        <td>{{ companyInfo.cityRegistration }}</td>
        <td>{{ companyInfo.shareSocial }}</td>
        <td>{{ companyInfo.jurisdiction.name }}</td>
        <td>{{ companyInfo.createdAt|date('d-m-Y H:i:s') }}</td>
    </tr>

templates/historical/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Company historical'|trans}}{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
                <div class="form-row align-items-end">
                    <div class="col">
                        {{ form_row(form.created_at) }}
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <button class="btn btn-primary">Rechercher</button>
                        </div>
                    </div>
                </div>
            {{ form_end(form) }}
        </div>
    </div>

    <div class="container mt-4">
        <div class="text-primary" style="font-weight: bold;font-size: 4rem;"><h1>{{ 'Company historical'|trans}}</h1></div>
        </br>
            <div class="container mt-4">
                <div class="text-primary" style="font-weight: bold;font-size: 4rem;"><h1>{{ 'Info'|trans}}</h1></div>
                </br>
                     <div class="row">
                         <table class="table">
                             <thead>
                                 <tr>
                                     <th>{{ 'Name'|trans}}</th>
                                     <th>{{ 'Siren number'|trans}}</th>
                                     <th>{{ 'City registration'|trans}}</th>
                                     <th>{{ 'Share social'|trans}}</th>
                                     <th>{{ 'Legal form'|trans}}</th>
                                     <th>{{ 'Modification Date'|trans}}</th>
                                 </tr>
                             </thead>
                            <tbody>
                                {% for companyInfo in companyInfos %}
                                    {% include 'historical/_company.html.twig' %}
                                {% else %}
                                    <tr>
                                        <td colspan="3">{{ 'no records found'|trans}}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                         </table>
            </div>
    </div>
    </br>

    <div class="container mt-4">
    <div class="text-primary" style="font-weight: bold;font-size: 4rem;"><h1>{{ 'Company address history'|trans}}</h1></div>
        </br>
            <div class="container mt-4">
                <div class="text-primary" style="font-weight: bold;font-size: 4rem;"><h1>{{ 'Info'|trans}}</h1></div>
                </br>
                    <div class="row">
                         <table class="table">
                             <thead>
                                 <tr>
                                     <th>{{ 'Number'|trans}}</th>
                                     <th>{{ 'Way'|trans}}</th>
                                     <th>{{ 'Street_name'|trans}}</th>
                                     <th>{{ 'Postal_code'|trans}}</th>
                                     <th>{{ 'City'|trans}}</th>
                                     <th>{{ 'Modification Date'|trans}}</th>
                                 </tr>
                             </thead>
                            <tbody>
                                {% for addressInfo in addressInfos %}
                                    {% include 'historical/_address.html.twig' %}
                                {% else %}
                                    <tr>
                                        <td colspan="3">{{ 'no records found'|trans}}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                         </table>
                    </div>
            </div>
{% endblock %}