src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AddressRepository::class)
 */
class Address
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $number;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $way;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $street_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=Company::class, inversedBy="addresses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $company;

    /**
     * @ORM\OneToMany(targetEntity=HistoricalAddress::class, mappedBy="address")
     */
    private $historicalAddresses;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->historicalAddresses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(?int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getWay(): ?string
    {
        return $this->way;
    }

    public function setWay(string $way): self
    {
        $this->way = $way;

        return $this;
    }

    public function getStreetName(): ?string
    {
        return $this->street_name;
    }

    public function setStreetName(string $street_name): self
    {
        $this->street_name = $street_name;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    /**
     * @return Collection|HistoricalAddress[]
     */
    public function getHistoricalAddresses(): Collection
    {
        return $this->historicalAddresses;
    }

    public function addHistoricalAddress(HistoricalAddress $historicalAddress): self
    {
        if (!$this->historicalAddresses->contains($historicalAddress)) {
            $this->historicalAddresses[] = $historicalAddress;
            $historicalAddress->setAddress($this);
        }

        return $this;
    }

    public function removeHistoricalAddress(HistoricalAddress $historicalAddress): self
    {
        if ($this->historicalAddresses->removeElement($historicalAddress)) {
            // set the owning side to null (unless already changed)
            if ($historicalAddress->getAddress() === $this) {
                $historicalAddress->setAddress(null);
            }
        }

        return $this;
    }
}

src/Entity/Company.php
<?php

namespace App\Entity;

use App\Repository\CompanyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CompanyRepository::class)
 */
class Company
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=15)
     * @Assert\Length(min=9, max=15)
     */
    private $siren_number;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $city_registration;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_registration;

    /**
     * @ORM\Column(type="integer")
     */
    private $share_social;

    /**
     * @ORM\OneToMany(targetEntity=Address::class, mappedBy="company")
     */
    private $addresses;

    /**
     * @ORM\ManyToOne(targetEntity=Jurisdiction::class, inversedBy="companies")
     * @ORM\JoinColumn(nullable=false)
     */
    private $jurisdiction;

    /**
     * @ORM\OneToMany(targetEntity=HistoricalCompany::class, mappedBy="company")
     */
    private $historicalCompanies;

    /**
     * @ORM\OneToMany(targetEntity=HistoricalAddress::class, mappedBy="company")
     */
    private $historicalAddresses;


    public function __construct()
    {
        $this->date_registration = new \DateTime();
        $this->addresses = new ArrayCollection();
        $this->historicalCompanies = new ArrayCollection();
        $this->historicalAddresses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSirenNumber(): ?string
    {
        return $this->siren_number;
    }

    public function setSirenNumber(string $siren_number): self
    {
        $this->siren_number = $siren_number;

        return $this;
    }

    public function getCityRegistration(): ?string
    {
        return $this->city_registration;
    }

    public function setCityRegistration(string $city_registration): self
    {
        $this->city_registration = $city_registration;

        return $this;
    }

    public function getDateRegistration(): ?\DateTimeInterface
    {
        return $this->date_registration;
    }

    public function setDateRegistration(\DateTimeInterface $date_registration): self
    {
        $this->date_registration = $date_registration;

        return $this;
    }

    public function getShareSocial(): ?int
    {
        return $this->share_social;
    }

    public function setShareSocial(int $share_social): self
    {
        $this->share_social = $share_social;

        return $this;
    }

    /**
     * @return Collection|Address[]
     */
    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    public function addAddress(Address $address): self
    {
        if (!$this->addresses->contains($address)) {
            $this->addresses[] = $address;
            $address->setCompany($this);
        }

        return $this;
    }

    public function removeAddress(Address $address): self
    {
        if ($this->addresses->removeElement($address)) {
            // set the owning side to null (unless already changed)
            if ($address->getCompany() === $this) {
                $address->setCompany(null);
            }
        }

        return $this;
    }

    public function getJurisdiction(): ?Jurisdiction
    {
        return $this->jurisdiction;
    }

    public function setJurisdiction(?Jurisdiction $jurisdiction): self
    {
        $this->jurisdiction = $jurisdiction;

        return $this;
    }

    /**
     * @return Collection|HistoricalCompany[]
     */
    public function getHistoricalCompanies(): Collection
    {
        return $this->historicalCompanies;
    }

    public function addHistoricalCompany(HistoricalCompany $historicalCompany): self
    {
        if (!$this->historicalCompanies->contains($historicalCompany)) {
            $this->historicalCompanies[] = $historicalCompany;
            $historicalCompany->setCompany($this);
        }

        return $this;
    }

    public function removeHistoricalCompany(HistoricalCompany $historicalCompany): self
    {
        if ($this->historicalCompanies->removeElement($historicalCompany)) {
            // set the owning side to null (unless already changed)
            if ($historicalCompany->getCompany() === $this) {
                $historicalCompany->setCompany(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|HistoricalAddress[]
     */
    public function getHistoricalAddresses(): Collection
    {
        return $this->historicalAddresses;
    }

    public function addHistoricalAddress(HistoricalAddress $historicalAddress): self
    {
        if (!$this->historicalAddresses->contains($historicalAddress)) {
            $this->historicalAddresses[] = $historicalAddress;
            $historicalAddress->setCompany($this);
        }

        return $this;
    }

    public function removeHistoricalAddress(HistoricalAddress $historicalAddress): self
    {
        if ($this->historicalAddresses->removeElement($historicalAddress)) {
            // set the owning side to null (unless already changed)
            if ($historicalAddress->getCompany() === $this) {
                $historicalAddress->setCompany(null);
            }
        }

        return $this;
    }
}

src/Form/CompanyType.php
<?php

namespace App\Form;

use App\Entity\Company;
use App\Entity\Jurisdiction;
use App\Repository\JurisdictionRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class CompanyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('siren_number')
            ->add('city_registration')
            ->add('share_social')
            ->add('jurisdiction', EntityType::class, [
                'class'    => Jurisdiction::class,
                'choice_label' => 'name',
                'query_builder' => function(JurisdictionRepository $repo) {
                 return $repo->createQueryBuilder('j')
                ->orderBy('j.name', 'ASC');
                }
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Company::class,
            'translation_domain' => 'forms'
        ]);
    }
}

src/Controller/CompanyController.php
<?php

namespace App\Controller;

use App\Entity\Company;
use App\Form\CompanyType;
use App\Repository\CompanyRepository;
use App\Entity\HistoricalCompany;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/company")
 */
class CompanyController extends AbstractController
{
    /**
     * @Route("/", name="company_index", methods={"GET"})
     */
    public function index(CompanyRepository $companyRepository): Response
    {
        return $this->render('company/index.html.twig', [
            'current_menu' => 'companies',
            'companies' => $companyRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="company_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $company = new Company();
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($company);
            $entityManager->flush();

            return $this->redirectToRoute('company_index');
        }

        return $this->render('company/new.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="company_show", methods={"GET"})
     */
    public function show(Company $company): Response
    {
        return $this->render('company/show.html.twig', [
            'company' => $company,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="company_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Company $company): Response
    {
        $historical = new HistoricalCompany();
        $historical->setName($company->getName());
        $historical->setSirenNumber($company->getSirenNumber());
        $historical->setCityRegistration($company->getCityRegistration());
        $historical->setShareSocial($company->getShareSocial());
        $historical->setCompany($company);
        $historical->setJurisdiction($company->getJurisdiction());
        $this->getDoctrine()->getManager()->persist($historical);

        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('company_index');
        }

        return $this->render('company/edit.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="company_delete", methods={"POST"})
     */
    public function delete(Request $request, Company $company): Response
    {
        if ($this->isCsrfTokenValid('delete'.$company->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($company);
            $entityManager->flush();
        }

        return $this->redirectToRoute('company_index');
    }
}

templates/company/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/company/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Edit Company'|trans}}{% endblock %}

{% block body %}
    <div class="container mt-4">
        <div class="text-primary" style="font-weight: bold;font-size: 4rem;"><h1>{{ 'Edit Company'|trans}}</h1></div>

        {{ include('company/_form.html.twig', {'button_label': 'Enregistrer'}) }}

        <div class="text-right">
            <a href="{{ path('company_index') }}" class="btn btn-primary">{{ 'Back to list'|trans}}</a>
        </div>

    </div>
{% endblock %}

templates/company/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Company index'|trans}}{% endblock %}

{% block body %}
    <div class="container mt-4">
    <div class="text-primary" style="font-weight: bold;font-size: 4rem;"><h1>{{ 'Company index'|trans}}</h1></div>

    <table class="table">
        <thead>
            <tr>
                <th>{{ 'Name'|trans}}</th>
                <th>{{ 'Legal form'|trans}}</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for company in companies %}
            <tr>
                <td>{{ company.name }}</td>
                <td>{{ company.jurisdiction.name }}</td>
                <td>
                    <a href="{{ path('company_show', {'id': company.id}) }}" class="btn btn-primary">{{ 'Show'|trans}}</a>
                    <a href="{{ path('historical_show', {'id': company.id}) }}" class="btn btn-primary">{{ 'Historical'|trans}}</a>
                    <a href="{{ path('company_edit', {'id': company.id}) }}" class="btn btn-primary">{{ 'Edit'|trans}}</a>
                    <form method="post" action="{{ path('company_delete', {'id': company.id}) }}" style="display: inline-block" 
                    onsubmit="return confirm('Etes vous vraiment sûr?')">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ company.id) }}">
                    <button class="btn btn-danger">Supprimer</button>
                    </form>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">{{ 'no records found'|trans}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="text-right">
        <a href="{{ path('company_new') }}" class="btn btn-primary">{{ 'Create new company'|trans}}</a>
    </div>

    </div>

{% endblock %}

templates/company/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Create new company'|trans}}{% endblock %}

{% block body %}
    <div class="container mt-4">
    <div class="text-primary" style="font-weight: bold;font-size: 4rem;"><h1>{{ 'Create new company'|trans}}</h1></div>

        {{ include('company/_form.html.twig') }}

        <div class="text-right">
            <a href="{{ path('company_index') }}" class="btn btn-primary">{{ 'Back to list'|trans}}</a>
        </div>

    </div>
{% endblock %}

templates/company/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Company'|trans}}{% endblock %}

{% block body %}
    <div class="container mt-4">
    <div class="text-primary" style="font-weight: bold;font-size: 4rem;"><h1>{{ 'Company'|trans}} {{ company.name }}</h1></div>

        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <th>{{ 'Name'|trans}}</th>
                    <th>{{ 'Siren number'|trans}}</th>
                    <th>{{ 'City registration'|trans}}</th>
                    <th>{{ 'Share social'|trans}}</th>
                    <th>{{ 'Date registration'|trans}}</th>
                </tr>
                <tr>
                    <td>{{ company.id }}</td>
                    <td>{{ company.name }}</td>
                    <td>{{ company.sirenNumber }}</td>
                    <td>{{ company.cityRegistration }}</td>
                    <td>{{ company.shareSocial }}</td>
                    <td>{{ company.dateRegistration|date('d-m-Y H:i:s') }}</td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="container mt-4">
        <div class="text-primary" style="font-weight: bold;font-size: 4rem;"><h1>{{ 'Show all addresses'|trans}}</h1></div>
        </br>
            <div class="row">
                {% if company.addresses is empty %}
                    <tr>
                        <td colspan="3">{{ 'no records found'|trans}}</td>
                    </tr>
                {% else %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>{{ 'Number'|trans}}</th>
                            <th>{{ 'Way'|trans}}</th>
                            <th>{{ 'Street_name'|trans}}</th>
                            <th>{{ 'Postal_code'|trans}}</th>
                            <th>{{ 'City'|trans}}</th>
                        </tr>
                    </thead>
                    <tbody>
                {% for address in company.addresses %}
                        <tr>
                            <td>{{ address.id }}</td>
                            <td>{{ address.number }}</td>
                            <td>{{ address.way }}</td>
                            <td>{{ address.streetName }}</td>
                            <td>{{ address.postalCode }}</td>
                            <td>{{ address.city }}</td>
                        </tr>
                {% endfor %}
                    </tbody>
                </table>
                {% endif %}
            </div>

        <div class="text-right">
            <a href="{{ path('company_index') }}" class="btn btn-primary">{{ 'Back to list'|trans}}</a>
        </div>
    </div>
{% endblock %}